# Nombre lógico de la aplicación
spring.application.name=ms-reportes

# Puerto del microservicio
server.port=8081

# URL de conexión mapeada a tu archivo .env
spring.datasource.url=${SPRING_DATASOURCE_URL_REPORTES}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Configuración de Conexión a Apache Kafka
spring.kafka.bootstrap-servers=kafka:9092

# Configuramos los serializadores (Transforman el objeto Java a bytes para enviarlo por la red)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer