# Nombre lógico del microservicio
spring.application.name=ms-usuarios

# Puerto del microservicio de usuarios
server.port=8082

# URL de conexión mapeada a tu archivo .env
spring.datasource.url=${SPRING_DATASOURCE_URL_USUARIOS}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true