# Nombre lógico del microservicio
spring.application.name=ms-usuarios

# Puerto del microservicio de usuarios
server.port=8082

# URL interna del contenedor PostgreSQL de usuarios.
spring.datasource.url=jdbc:postgresql://postgres-usuarios:5432/usuarios_db
spring.datasource.username=valle_user
spring.datasource.password=valle_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true