apiVersion: v1
kind: Secret
metadata:
  name: valle-secrets
  namespace: valle-del-sol
type: Opaque
data:
  # valle_user en Base64
  POSTGRES_USER: dmFsbGVfdXNlcg==
  
  # valle_pass_2026 en Base64
  POSTGRES_PASSWORD: dmFsbGVfcGFzc18yMDI2
  
  # NUj5SYvv0DYb895RqG3G1mpkB+oH0Sr19fNWm0E6Jos= en Base64
  JWT_SECRET: TlVqNVNZdnYwRlliODk1UnFHM0cxbXBrQitvSDBScjE5Zk5XbTBFNkpvcz0=
