# Puerto exclusivo de Monitoreo Geografico
server.port=8086
spring.application.name=ms-geografico

# Base de datos dedicada (Patrón Database-per-Microservice)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/geografico_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:valle_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:valle_pass}

# Sincronización de tablas de coordenadas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración del Consumidor de Apache Kafka
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.consumer.group-id=valle-sol-geografico-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=cl.valledelsol.ms_geografico.dto