# =========================================================
# CONFIGURACIÓN INTERNA DEL MICROSERVICIO DE AUTENTICACIÓN
# =========================================================

# Puerto exclusivo para el servicio de seguridad (Feedback del profesor)
server.port=8083

# Nombre con el que se identifica este módulo en la red Docker
spring.application.name=ms-auth

# URL de conexión a la base de datos de seguridad (Usa variables de entorno de Docker)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:valle_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:valle_pass}

# Configuración de Hibernate para auto-crear las tablas en la base de datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect