# =========================================================
# CONFIGURACIÓN INTERNA DEL MICROSERVICIO DE AUTENTICACIÓN
# =========================================================

# Puerto exclusivo para el servicio de seguridad
server.port=8083

# Nombre con el que se identifica este módulo en la red Docker
spring.application.name=ms-auth

# 🔑 CORREGIDO: Apunta al contenedor postgres-usuarios y a la base de datos usuarios_db
spring.datasource.url=jdbc:postgresql://postgres-usuarios:5432/usuarios_db
spring.datasource.username=valle_user
spring.datasource.password=valle_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect