# Nombre lógico del BFF
spring.application.name=bff-valle-sol

# Puerto del BFF
server.port=8080


# =========================================================
# COORDINADAS DE ADUANAS MUNICIPALES ruta mapeada en .env
# =========================================================
# Modificamos las rutas apuntando a la estructura /api/v1/ de Kong
services.reportes.url=${MS_REPORTES_URL:http://localhost:8000/api/v1/reportes}
services.usuarios.url=${MS_USUARIOS_URL:http://localhost:8000/api/v1/usuarios}
services.analitica.url=${MS_ANALITICA_URL:http://localhost:8000/api/v1/analitica}
services.geografico.url=${MS_GEOGRAFICO_URL:http://localhost:8000/api/v1/geografia}
