    # Nombre lógico del BFF
    spring.application.name=bff-valle-sol

    # Puerto del BFF
    server.port=8080


    # =========================================================
    # COORDINADAS DE ADUANAS MUNICIPALES ruta mapeada en .env
    # =========================================================
    # Modificamos las rutas apuntando a la estructura /api/v1/ de Kong
    ##services.reportes.url=${MS_REPORTES_URL:http://ms-reportes:8080}
    ##services.usuarios.url=${MS_USUARIOS_URL:http://ms-usuarios:8080}
    ##services.analitica.url=${MS_ANALITICA_URL:http://ms-analitica:8080}
    ##services.geografico.url=${MS_GEOGRAFICO_URL:http://ms-geografico:8080}


    ms.analitica.url=${MS_ANALITICA_URL:http://ms-analitica:8085}
    ms.geografico.url=${MS_GEOGRAFICO_URL:http://ms-geografico:8086}
    ms.alertas.url=${MS_ALERTAS_URL:http://ms-alertas:8084}
    ms.auth.url=${MS_AUTH_URL:http://ms-auth:8083}
    app.jwt.secret=${JWT_SECRET:NUj5SYvv0DYb895RqG3G1mpkB+oH0Sr19fNWm0E6Jos=}
