# Nombre lógico del BFF
spring.application.name=bff-valle-sol

# Puerto del BFF
server.port=8080

# URLs internas de los microservicios
services.reportes.url=http://localhost:8081/api/reportes
services.usuarios.url=http://localhost:8082/api/usuarios