apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: valle-del-sol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "usuarios_db"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: valle-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: valle-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        # Monta el script de inicialización de múltiples bases de datos
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-sql
