# Nombre del flujo de trabajo que se mostrará en la pestaña "Actions" de GitHub
name: CI/CD Valle del Sol - AWS ECR

# Definición de disparadores (Triggers)
on:
  push:
    branches:
      - develop # El pipeline se activará automáticamente al hacer 'git push' a esta rama

jobs:
  # Definición del trabajo para compilar y subir las imágenes
  build-and-push:
    name: Compilar y Subir Microservicios
    runs-on: ubuntu-latest
    
    # Estrategia de matriz para procesar los microservicios en paralelo
    strategy:
      matrix:
        service: [bff-valle-sol, ms-reportes, ms-usuarios, ms-auth, ms-geografico, ms-alertas, ms-analitica, frontend-valle-sol] # Lista de carpetas de los microservicios

    steps:
      # Paso 1: Clonar el código del repositorio en la máquina virtual de GitHub actions
      - name: Descargar Código del Repositorio
        uses: actions/checkout@v4

      # Paso 2: Configurar credenciales de AWS usando los secretos de GitHub
      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Paso 3: Autenticarse en Amazon ECR
      - name: Iniciar Sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Paso 4: Configurar Docker Buildx (Herramienta para optimizar la construcción y manejo de caché)
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso 5: Compilar el código y subir la imagen construida a Amazon ECR
      - name: Construir y Publicar Imagen en Amazon ECR
        uses: docker/build-push-action@v5
        with:
          # Define el contexto de ejecución apuntando a la carpeta específica del microservicio actual de la matriz
          context: ./${{ matrix.service }}
          # Ruta explícita del Dockerfile a utilizar
          file: ./${{ matrix.service }}/Dockerfile
          # Indica que una vez construida con éxito, la imagen debe subirse (push) inmediatamente a ECR
          push: true
          # Etiquetas (Tags) con las que se guardará la imagen en tu registro de Amazon ECR
          tags: |
            473818454094.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.service }}:latest
            473818454094.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.service }}:develop
            473818454094.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.service }}:${{ github.sha }}
